### ISSUE TITLE
Corrections diverses de classes et sorts

### ISSUE THREAD

**Issue by Angor-de-Redjak** [rwanoux/SRD-Heros-et-Dragons#1]
J'ai fait une passe non-exhaustive sur pas mal de classes et capacités de classes.

- Flamme sacrée : changement de l'évolution de niveau en sorts mineurs
- Bouffée de poison : changement de l'évolution de niveau en sorts mineurs
- Barde : correction progression, chant reposant à partir du niveau 2 au lieu du 1 + passage au d8 au niveau 9 au lieu du niv8
- Inspiration bardique : correction de la portée en mètres + repos long
- Collège des taromanciens : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Barbare : correction progression dégâts rage +3 au niveau 9 au lieu du niv 10 + ajout nombre de rages dans la progression
- Voie de la bête : rajout d'un tag + remise en page
- Ajout de l'entrée Lien spirituel pour la voie des esprits du Barbare
- Forme animale : remise en page
- Voie des steppes : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Voie des glaces : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Souffle de givre : l'entrée était vide, lol. Du coup je l'ai remplie.
- Cercle sans nom : création de l'entrée en tant que sous-classe
- Cercle druidique : ajout du cercle sans nom
- Rajout du tag [Officier] dans le nom des capacités de l'archétype Officier du guerrier.
- Officier : Update des noms des capacités suite au point ci-dessus + intégration dés de commandement dans la progression de l'archétype.
- Inspiration guerrière : remise en page de la description + ajout lancer de dés + repos court
- Maître d'armes : rajout de la durée = bonus de maîtrise
- Alerte réactive : rajout du coût en action + lancer de dé
- Action coordonnée : rajout d'un point dans la description + portée/cible
- Sursaut d'activité : rajout du nombre d'utilisations
- Maître d'étude : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Simulacre : remise en page de la description
- Moine : correction progression des points de ki
- Ki : intégration des objets des aptitudes de ki dans le récap du ki + remise en page des aptitudes de Ki
- Parade de projectiles : ajout cible
- Chute ralentie : rajout cible
- Frappe étourdissante : rajout cible
- Voie de l'illumination : modif de la description pour préciser que les aptitudes des niveaux 11 et 17 sont bien présents.
- Tranquillité de l'esprit : ajout cible + action
- Sens divin : ajout portée + cible
- Imposition des mains : ajout nb utilisations max + cible/portée et repos long
- Serment de justice : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Passeur : rajout du tag de l'archétype sur les aptitudes et dans la description.
- Ouïe fine : réglage de la portée
- Protecteur de l'Outre-monde : intégration des liens d'objets Protecteurs
- Réparation icône : réaction violente, migration d'été, frappe lumineuse, lueur d'espoir, réincarnation, résurrection suprême, revigorer, sanctification, sphère de feu

En bonus : dans le compendium des Capacités de classe, y a un sort de flèche arcanique qui traîne, autre que la capacité du rôdeur. Je ne sais pas si c'est normal...
[corrections_fichiers_db.zip](https://github.com/rwanoux/SRD-Heros-et-Dragons/files/10938934/corrections_fichiers_db.zip)

**Comment by Padhiver** [comment]
C'est ajouté !
