### ISSUE TITLE
Content of compendium "Capacités de classes" been replaced by content of compendium "Classes et spécialisations"

### ISSUE THREAD

**Issue by Zaitazu4590** [rwanoux/SRD-Heros-et-Dragons#2]
As stated in the title, the content of the "Capacités de classes" compendium has been replaced by the content of the "Classes et spécialisations" compendium. It is no longer possible to access the class abilities (broken links).

![Capture](https://user-images.githubusercontent.com/127511585/224335156-2f82fa42-cdc1-400d-9b86-e2c67288b130.PNG)

**Comment by Padhiver** [comment]
Fixed! (normally)
