### ISSUE TITLE
Compatible avec foundryVTT 10.283+ ?

### ISSUE THREAD

**Issue by nicolasbraun** [rwanoux/SRD-Heros-et-Dragons#4]
Hello,

Peut-être que je rate quelque chose mais si j'installe foundry 10.282 alors aucun module n'est disponible à l'install.
J'ai donc pris la derniere (291) et la 283, installé le module H&D mais j'ai beau l'activer sur un World tout bête je ne vois rien dans l'interface.

Je rate quelque chose?

Merci

![image](https://github.com/rwanoux/SRD-Heros-et-Dragons/assets/1089363/ac273004-8fe2-4f22-8c81-16558ba86491)

**Comment by nicolasbraun** [comment]
Je précise que je vois bien le Compendium mais pas tout le reste (icone en haut a droite, cheatsheet en bas...)

**Comment by rwanoux** [comment]
Le module a été extrêmement épuré. Il ne contient quasiment plus que les compendiums. Ceci dans l'attente d'un nouveau module qui prendra en parti le relai.
